apiVersion: v1
kind: Service
metadata:
  name: openfire
spec:
  type: NodePort
  selector:
    app: openfire
  ports:
    - name: admin-http
      port: 9090
      targetPort: 9090
      nodePort: 30090

    - name: admin-https
      port: 9091
      targetPort: 9091
      nodePort: 30091

    - name: xmpp
      port: 5222
      targetPort: 5222
      nodePort: 30522

    - name: http-bind
      port: 7070
      targetPort: 7070
      nodePort: 30070
