apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: nifi
spec:
  type: ClusterIP
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
      targetPort: 8443
    - name: cluster-protocol
      port: 11443
      targetPort: 11443
