apiVersion: v1
kind: Service
metadata:
  name: nifi-nodeport
  namespace: nifi-a
spec:
  type: NodePort
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 31000
