apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-conf-pvc
  namespace: nifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nifi-storage-conf
  resources:
    requests:
      storage: 5Gi
