apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  template:
    spec:
      containers:
        - name: nifi
          volumeMounts:
            - name: nifi-data
              mountPath: /opt/nifi/nifi-current/data
