apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      initContainers:
        - name: busybox
          image: busybox-image
          command:
            - sh
            - -c
            - |
              echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
              until nc -vzw 1 zookeeper 2181 ; do
                echo "Waiting for zookeeper to start"
                sleep 3
              done
      containers:
        - name: nifi
          image: nifi-image
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: nifi-cm
            - secretRef:
                name: nifi-auth

          volumeMounts:
            - name: nifi-cert
              mountPath: /opt/nifi/tls
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/flowfile_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/content_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/provenance_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/database_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/state

      volumes:
        - name: nifi-cm
          configMap:
            name: nifi-cm
        - name: nifi-cert
          secret:
            secretName: nifi-tls
        - name: nifi-pvc
          persistentVolumeClaim:
            claimName: nifi-pvc
