apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: nifi
  name: nifi
spec:
  serviceName: nifi-headless
  replicas: 2
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      subdomain: nifi-headless
      initContainers:
        - name: busybox
          image: busybox-image
          command:
            - sh
            - -c
            - |
              echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
              until nc -vzw 1 zookeeper 2181 ; do
                echo "Waiting for zookeeper to start"
                sleep 3
              done
      containers:
        - name: nifi
          image: nifi-image
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 11443
              name: cluster
          envFrom:
            - configMapRef:
                name: nifi-cm
            - secretRef:
                name: nifi-auth

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          volumeMounts:
            - name: nifi-cert
              mountPath: /opt/nifi/tls
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/flowfile_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/content_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/provenance_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/database_repository
            - name: nifi-pvc
              mountPath: /opt/nifi/nifi-current/state

      volumes:
        - name: nifi-cm
          configMap:
            name: nifi-cm
        - name: nifi-cert
          secret:
            secretName: nifi-tls
        - name: nifi-pvc
          persistentVolumeClaim:
            claimName: nifi-pvc
