apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  namespace: nifi
spec:
  clusterIP: None
  selector:
    app: nifi
  ports:
    - name: cluster
      port: 11443
      targetPort: 11443
