apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      initContainers:
        - name: busybox
          image: busybox-image
          command:
            - sh
            - -c
            - |
              echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
              until nc -vzw 1 zookeeper 2181 ; do
                echo "Waiting for zookeeper to start"
                sleep 3
              done
      containers:
        - name: nifi
          image: nifi-image
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: nifi-config
            - secretRef:
                name: nifi-auth
          volumeMounts:
            - name: flowfile-repo
              mountPath: /opt/nifi/nifi-current/flowfile_repository
            - name: content-repo
              mountPath: /opt/nifi/nifi-current/content_repository
            - name: provenance-repo
              mountPath: /opt/nifi/nifi-current/provenance_repository
            - name: database-repo
              mountPath: /opt/nifi/nifi-current/database_repository
            - name: state
              mountPath: /opt/nifi/nifi-current/state

          startupProbe:
            tcpSocket:
              port: 8443
            failureThreshold: 60
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 300
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: flowfile-repo
          emptyDir: { }
        - name: content-repo
          emptyDir: { }
        - name: provenance-repo
          emptyDir: { }
        - name: database-repo
          emptyDir: { }
        - name: state
          emptyDir: { }
