apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      initContainers:
        - name: busybox
          image: busybox-image
          command:
            - sh
            - -c
            - |
              until nc -z zookeeper 2181; do
                echo "Waiting for Zookeeper..."
                sleep 5
              done
      containers:
        - name: nifi
          image: nifi-image
          ports:
            - containerPort: 8443
            - containerPort: 11443
          envFrom:
            - configMapRef:
                name: nifi-config
            - secretRef:
                name: nifi-auth
      volumes:
        - name: tls
          secret:
            secretName: nifi-tls
