apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi:2.7.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: content-repo
              mountPath: /opt/nifi/nifi-current/content_repository
            - name: provenance-repo
              mountPath: /opt/nifi/nifi-current/provenance_repository
            - name: flowfile-repo
              mountPath: /opt/nifi/nifi-current/flowfile_repository
            - name: database-repo
              mountPath: /opt/nifi/nifi-current/database_repository
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /nifi-api/system-diagnostics
              port: 8443
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /nifi-api/system-diagnostics
              port: 8443
            initialDelaySeconds: 300
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
          startupProbe:
            httpGet:
              scheme: HTTPS
              path: /nifi-api/system-diagnostics
              port: 8443
            failureThreshold: 60
            periodSeconds: 10
          env:
            - name: NIFI_WEB_HTTP_PORT
              value: "8080"
            - name: NIFI_WEB_HTTPS_PORT
              value: "8443"
            - name: NIFI_CLUSTER_IS_NODE
              value: "true"
            - name: NIFI_ZOOKEEPER_CONNECT_STRING
              value: "zookeeper:2181"
            - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
              value: "9999"
      initContainers:
        - name: wait-for-zookeeper
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              until nc -z zookeeper 2181; do
                echo "Waiting for Zookeeper..."
                sleep 5
              done
      volumes:
        - name: content-repo
          emptyDir: {}
        - name: provenance-repo
          emptyDir: {}
        - name: flowfile-repo
          emptyDir: {}
        - name: database-repo
          emptyDir: {}
