apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openfire-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfire
  template:
    metadata:
      labels:
        app: openfire
    spec:

      containers:
        - name: openfire
          image: openfire:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 9090
            - containerPort: 5222
            - containerPort: 7070

          volumeMounts:
            - name: openfire-data
              mountPath: /var/lib/openfire

      volumes:
        - name: openfire-data
          persistentVolumeClaim:
            claimName: openfire-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: openfire
spec:
  type: ClusterIP
  selector:
    app: openfire
  ports:
    - name: admin
      port: 9090
      targetPort: 9090
    - name: xmpp
      port: 5222
      targetPort: 5222
