apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openfire2

resources:
  - namespace.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: openfire
      app.kubernetes.io/component: xmpp-server
