---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-registry-config
  namespace: nifi
data:
  nifi-registry.properties: |
    nifi.registry.web.http.port=18080
    nifi.registry.web.https.port=
    nifi.registry.security.keystore=
    nifi.registry.security.truststore=
    nifi.registry.db.url=jdbc:h2:./database/nifi-registry.db
    nifi.registry.flow.persistence.provider=flowPersistenceProvider
    nifi.registry.flow.persistence.provider.flowPersistenceProvider.implementation=org.apache.nifi.registry.provider.flow.FileSystemFlowPersistenceProvider
    nifi.registry.flow.persistence.provider.flowPersistenceProvider.properties.flowStorageDirectory=./flow_storage


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-registry-pvc
  namespace: nifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-registry
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi-registry
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      containers:
        - name: registry
          image: apache/nifi-registry:1.25.0
          ports:
            - containerPort: 18080

          env:
            - name: NIFI_REGISTRY_WEB_HTTP_PORT
              value: "18080"
          volumeMounts:
            - name: registry-data
              mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
            - name: registry-data
              mountPath: /opt/nifi-registry/nifi-registry-current/database
            - name: registry-config
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/nifi-registry.properties
              subPath: nifi-registry.properties
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: nifi-registry-pvc
        - name: registry-config
          configMap:
            name: nifi-registry-config


---
apiVersion: v1
kind: Service
metadata:
  name: nifi-registry-nodeport
  namespace: nifi
spec:
  type: NodePort
  selector:
    app: nifi-registry
  ports:
    - name: http
      port: 18080
      targetPort: 18080
      nodePort: 31880
