# =========================
# Namespace
# =========================
apiVersion: v1
kind: Namespace
metadata:
  name: nifi
---
# =========================
# NiFi Credentials Secret
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: nifi-secret
  namespace: nifi
type: Opaque
stringData:
  NIFI_USERNAME: admin
  NIFI_PASSWORD: Admin123456!
---
# =========================
# ZooKeeper (single node)
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.9.1
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: nifi
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
# =========================
# NiFi ConfigMap
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-config
  namespace: nifi
data:
  NIFI_WEB_HTTPS_PORT: "8443"
  NIFI_CLUSTER_IS_NODE: "true"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: "11443"
  NIFI_ZK_CONNECT_STRING: "zookeeper:2181"
  NIFI_ELECTION_MAX_WAIT: "1 min"
  NIFI_CLUSTER_LEADER_ELECTION_IMPLEMENTATION: "org.apache.nifi.controller.leader.election.zookeeper.ZooKeeperLeaderElectionManager"
  NIFI_CLUSTER_LEADER_ELECTION_KUBERNETES_ENABLED: "false"
---
# =========================
# NiFi Headless Service
# (pod-to-pod communication)
# =========================
apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: nifi
spec:
  clusterIP: None
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
    - name: cluster
      port: 11443
---
# =========================
# NiFi NodePort Service (UI)
# =========================
apiVersion: v1
kind: Service
metadata:
  name: nifi-nodeport
  namespace: nifi
spec:
  type: NodePort
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30443
---
# =========================
# NiFi StatefulSet (Cluster)
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      initContainers:
        - name: busybox
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
              until nc -vzw 1 zookeeper 2181 ; do
                echo "Waiting for zookeeper to start"
                sleep 3
              done
      containers:
        - name: nifi
          image: apache/nifi:2.7.2
          ports:
            - containerPort: 8443
            - containerPort: 11443
          envFrom:
            - configMapRef:
                name: nifi-config
          env:
            - name: NIFI_WEB_HTTPS_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: SINGLE_USER_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nifi-secret
                  key: NIFI_USERNAME

            - name: SINGLE_USER_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nifi-secret
                  key: NIFI_PASSWORD
