---

#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: zookeeper-namespace-only
#  namespace: nifi
#spec:
#  podSelector:
#    matchLabels:
#      app: zookeeper
#  policyTypes:
#    - Ingress
#  ingress:
#    - from:
#        - podSelector:
#            matchLabels:
#              app: nifi
#      ports:
#        - protocol: TCP
#          port: 2181

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: nifi
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.9.1
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: nifi
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
