apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inspire-silrelease

resources:
  - namespace.yaml
  - rbac.yaml
  - password-secret.yaml
  - cert-generation-job.yaml
  - statefulset.yaml
  - service-headless.yaml
  - service-nodeport.yaml
  - configmap.yaml
  - pv-pvc.yaml
