apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-flowfiles-pv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nifi/flowfiles
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-content-pv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nifi/content
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-provenance-pv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nifi/provenance
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-database-pv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nifi/database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-flowfiles-pvc
  namespace: inspire-silrelease
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-content-pvc
  namespace: inspire-silrelease
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-provenance-pvc
  namespace: inspire-silrelease
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-database-pvc
  namespace: inspire-silrelease
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
