apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  namespace: inspire-silrelease
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterIP: None
  selector:
    app: nifi
  ports:
    - port: 8443
      name: https
    - port: 10000
      name: site-to-site
