apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: placeholder/zookeeper   # overridden from root
          ports:
            - containerPort: 2181
      volumes:
        - name: tls
          secret:
            secretName: zk-tls
