apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inspire-silrelease

bases:
  - ../../base

namePrefix: nifi-black-

patches:
  - path: patches/patch-statefulset.yaml
    target:
      kind: StatefulSet
      name: nifi
  - path: patches/patch-configmap.yaml
    target:
      kind: ConfigMap
      name: nifi-config
  - path: patches/patch-job.yaml
    target:
      kind: Job
      name: nifi-cert-generator
  - path: patches/patch-password-secret.yaml
    target:
      kind: Secret
      name: nifi-cert-pass
