apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: nifi
  replicas: 1   # placeholder overridden by root kustomization
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z zookeeper 2181; do
                echo "Waiting for Zookeeper..."
                sleep 5
              done
      containers:
        - name: nifi
          image: apache/nifi   # placeholder
          ports:
            - containerPort: 8443
            - containerPort: 11443
          envFrom:
            - configMapRef:
                name: nifi-config
            - secretRef:
                name: nifi-auth
      volumes:
        - name: tls
          secret:
            secretName: nifi-tls
